# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d0ac89c24af090ff84dfa9e3d3f242e87ace7828f34172fc560e7b68631cc7afcee4a14a8fcc19b2bba4d29543421af75c8955e3ec118d354227df359d8a9ae

test:
  secret_key_base: 3e7bd1815c151a14155dce0151c058384e89e0b50b27d389b20e07974d01e1eef334478e00fcd8616da8deffe80fb5af69b1f2f8f760a5089160f8ec2d228a22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
